### ISSUE TITLE
Transparent background issue

### ISSUE THREAD

**Issue by PaulPauler** [jpcurrier/simple-slide-show#1]
Transparent background makes all figures appear mixed right after loading. Seems like need to add 'display:none' class after init to each slide except first, and remove it right before according slide begin (or control pressed).

**Comment by jpcurrier** [comment]
Thanks, @PaulPauler. There was an issue with the loading state: all slides should've been obscured by a loading graphic until the slide-show loaded, but there was a bit of missing styling. I just pushed an update that should take care of this and simplifies a few related layout procedures.

**Comment by PaulPauler** [comment]
Thanks for update, but problem still occurs. Maybe this gif will help you to realize :)
![anim](https://cloud.githubusercontent.com/assets/3423679/19716290/652c7218-9b74-11e6-99ef-1c37768e559e.gif)

**Comment by jpcurrier** [comment]
@PaulPauler, can you apply a white background-color to the slides? Let me know if that does not work for you.

**Comment by PaulPauler** [comment]
> can you apply a white background-color to the slides?

Nope, I indicate in issue exactly transparent background as a requirement. For example, you have layout with static background-image and want slides to act over it. Slide's colored background will override layout, thats why transparency needed. Thanks

**Comment by jpcurrier** [comment]
Gotcha. I pushed a few changes that should enable you to use transparent slides. Let me know if you're still having issues with the latest commit.

**Comment by PaulPauler** [comment]
Looking fine for the 'slide' effect with transparency, thanks for your tenderness! :)

**Comment by jpcurrier** [comment]
My pleasure. I appreciate your input.
